### ISSUE TITLE
register_module('import_off'): defines no classes

### ISSUE THREAD

**Issue by lethal233** [davidstutz/bpy-visualization-utils#4]
Hello, I have trouble with this problem for many days, and there is few possible solutions to it.

When I run the code in the shell `blender --background --python render_off.py -- --off examples/0.off --output examples/0.png`, it gives me the feedback:

```shell
Traceback (most recent call last):
  File "/media/renwen/21EC3ABD229B0E60/project/cvpr2018shapecompletion/bpy-visualization-utils-master/render_off.py", line 6, in <module>
    from blender_utils import *
  File "/media/renwen/21EC3ABD229B0E60/project/cvpr2018shapecompletion/bpy-visualization-utils-master/blender_utils.py", line 67, in <module>
    import_off.register()
  File "/home/renwen/.config/blender/2.79/scripts/addons/import_off.py", line 171, in register
    bpy.utils.register_module(__name__)
  File "/usr/share/blender/scripts/modules/bpy/utils/__init__.py", line 684, in register_module
    raise Exception("register_module(%r): defines no classes" % module)
Exception: register_module('import_off'): defines no classes
```
This is the trouble that I met, and I don't know how to solve it. Would you like to tell me how to solve it?
I use your tools to help my projects on 3d reconstruction on pieces of chinaware.
Thanks a lot.
My email address is leemdragon233@yahoo.com.

**Comment by davidstutz** [comment]
Off import was originall taken from https://github.com/alextsui05/blender-off-addon as far as I remember. I didn't come across this problems before. As you arew using 2.79 I wouldn't expect any major problems though. Can you try using the verbose option in `register_module` (see https://docs.blender.org/api/blender_python_api_2_73a_release/bpy.utils.html#bpy.utils.register_module)  and see if it helps?

**Comment by lethal233** [comment]
> Off import was originall taken from https://github.com/alextsui05/blender-off-addon as far as I remember. I didn't come across this problems before. As you arew using 2.79 I wouldn't expect any major problems though. Can you try using the verbose option in `register_module` (see https://docs.blender.org/api/blender_python_api_2_73a_release/bpy.utils.html#bpy.utils.register_module) and see if it helps?

OK，I will try it. Thanks for the help 😊.
