### ISSUE TITLE
Black spots in the high-resolution Voxel 

### ISSUE THREAD

**Issue by LiyingCV** [davidstutz/bpy-visualization-utils#5]
Greetings, there are some black spots when I try to render a high-resolution voxel (The File type is .binvox). However, it is normal to render a low-resolution voxel (32^3). Could you tell me how to fix this problem? Thanks in advance.
![1](https://user-images.githubusercontent.com/46776337/155868739-783f1202-a9d8-443a-81ec-570e0c14232d.png)

**Comment by LiyingCV** [comment]
I solved it.

**Comment by davidstutz** [comment]
If you ever find your way back, please share your solution - would be interesting for others to know!

**Comment by LiyingCV** [comment]
Increase the scale can solve this problem!
